# Do not edit. Generated by the configure script.
export PATH:=/var/www/html/LaravelReactProject/node-v14.18.3/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.9
PREFIX=/usr/local
